# Generated by Django 5.0.6 on 2024-06-02 20:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("apellidos", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(default="cliente@cliente.cl", max_length=50),
                ),
                (
                    "edad",
                    models.IntegerField(
                        default=18,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("asunto", models.CharField(default="", max_length=200)),
                ("mensaje", models.TextField(default="", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Flan",
            fields=[
                (
                    "flan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("descripcion", models.TextField()),
                ("preparacion", models.TextField()),
                ("ingredientes", models.TextField()),
                ("img_url", models.ImageField(upload_to="static/flans/")),
                ("slug", models.SlugField()),
                ("is_private", models.BooleanField()),
            ],
        ),
    ]
