# Generated by Django 5.0.6 on 2024-05-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flan_id", models.UUIDField()),
                ("nombre", models.CharField(max_length=64)),
                ("descripcion", models.TextField()),
                ("preparacion", models.TextField()),
                ("ingredientes", models.TextField()),
                ("img_url", models.URLField()),
                ("slug", models.SlugField()),
                ("is_private", models.BooleanField()),
            ],
        ),
    ]
