# Generated by Django 5.0.6 on 2024-05-31 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_flan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flan",
            name="id",
        ),
        migrations.AlterField(
            model_name="flan",
            name="flan_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
