# Generated by Django 3.2.4 on 2024-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_flan_id_alter_flan_flan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='img_url',
            field=models.ImageField(upload_to='static/flans/'),
        ),
    ]
