# Generated by Django 5.0.6 on 2024-06-07 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_rename_customer_email_contactform_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactform",
            old_name="email",
            new_name="customer_email",
        ),
        migrations.RenameField(
            model_name="contactform",
            old_name="name",
            new_name="customer_name",
        ),
    ]
