# Generated by Django 3.2.4 on 2024-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_flan_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
