# Generated by Django 3.2.4 on 2024-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='cliente@cliente.cl', max_length=50),
        ),
    ]
