# Generated by Django 3.2.4 on 2024-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='asunto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mensaje',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
