# Generated by Django 3.2.4 on 2024-06-01 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_cliente_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contacto_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('nombres', models.CharField(default='', max_length=30)),
                ('apellidos', models.EmailField(default='', max_length=50)),
                ('asunto', models.CharField(default='', max_length=200)),
                ('mensaje', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mensaje',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
