# Generated by Django 3.2.4 on 2024-06-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20240601_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
